apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: team-a-prod
resources:
  - ../../base
patches:
  - patch: |
      - op: replace
        path: /spec/replicas
        value: 3
    target:
      kind: Deployment
      name: service-a
  - patch: |
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 100m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 128Mi
    target:
      kind: Deployment
      name: service-a
images:
  - name: quay.io/brancz/prometheus-example-app
    newTag: v0.5.0
