apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sidekick-monitoring
resources:
  # CRDs (must exist before controller starts).
  - https://raw.githubusercontent.com/slok/sloth/v0.11.0/pkg/kubernetes/gen/crd/sloth.slok.dev_prometheusservicelevels.yaml
  # Sloth controller deployment + RBAC.
  - https://raw.githubusercontent.com/slok/sloth/v0.11.0/deploy/kubernetes/raw/sloth.yaml
  - sidekick-slos.yaml
