apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sidekick-monitoring
resources:
  # Upstream Sloth controller (CRDs + deployment).
  - https://github.com/slok/sloth/releases/download/v0.11.0/sloth.yaml
  - sidekick-slos.yaml
