apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: team-a-staging
resources:
  - ../../base
patches:
  - patch: |
      - op: replace
        path: /spec/replicas
        value: 2
    target:
      kind: Deployment
      name: service-a
images:
  - name: quay.io/brancz/prometheus-example-app
    newTag: v0.5.0
